package com.chessmates.data

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName="DataItem")
class DataItem {
    private String id

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String getId(){
        return id
    }
}
